---
title: "Homework 2"
author: "Jonathan Hernandez"
date: "February 13, 2018"
output: html_document
---

2.6

a) The probability of getting a sum of 1 on a roll of a fair pair of dice is 0 as

the sample space when summing up the results never gives you 1 and is a event that

can't ever happen.

b) let E be the event of getting a sum of 5 on a fair roll of 2 dice.

then the sample space of rolling a pair of die is

{(1,1), (1,2), (1,3), (1,4), (1,5), (1,6), (2,1), (2,2), (2,3), (2,4), (2,5), (2,6),

(3,1), (3,2), (3,3), (3,4), (3,5), (3,6), (4,1), (4,2), (4,3), (4,4), (4,5), (4,6),

(5,1), (5,2), (5,3), (5,4), (5,5), (5,6), (6,1), (6,2), (6,3), (6,4), (6,5), (6,6)}

only way of getting a sum of 5 is if you roll (2,3), (3,2), (4,1), (1,4) so

P(E) = 4/36 = 1/9 or about 0.11 or 11% chance

c) Getting a sum of 12 can only be achieved by rolling (6,6) and

Probability is 1/36 or about 0.0278 or about 2.8% chance.

2.8

let A be the event that someone is living below the poverty line

let B be the event that someone speaks another language other than English

a) no they are not disjoint as being disjoint is such that 

P(living below the poverty line $\cap$ speaking a foreign language) = 0 which is

not the case.

b) Lets load up the VennDiagram Library to draw up the Venn Diagram

```{r load-venn-diagram-library, echo=TRUE}
if (!require(VennDiagram)) install.packages("VennDiagram")
library(VennDiagram)
draw.pairwise.venn(area1 = 18.8, area2 = 24.9, cross.area = 4.2, category = c("Live Below the Poverty Line", "Speak a Foreign Language"), cat.default.pos = 'text', cat.cex = 0.75)
```

c) Summarizing the problem in a probability sense the question is asking to find

P(A $\cap$ B') where B' is the complement of B.

P(B') =  1 - P(B) = 1 - 0.207 = .793 or about 80%

then P(A $\cap$ B') = P(A) - P(A $\cap$ B) = 0.146 - 0.042 =  0.104 or about 10.4%

d) The question is asking what is P(A $\cup$ B).

P(A $\cup$ B) = P(A) + P(B) - P(A $\cap$ B) = 0.146 + 0.207 - 0.042 = 0.311 or about 31.1%

e) The question is asking what is P(A' $\cap$ B').

P(A' $\cap$ B') = P( (A $\cup$ B)' ) where ' is the complement and using the complement rule,

P( (A $\cup$ B)' ) = 1 - P(A $\cup$ B) = 1 - 0.311 = 0.689 or about 69%

f) To test for independence is to see if P(A $\cap$ B) = P(A)*P(B)

P(A)$\cdot$P(B) = 0.146*0.207 = 0.0302 which is not equal to 0.042 so the events are not independent.

2.20

a) Probability of a randomly chosen make has blue eyes or his partner does is

P(A $\cup$ B) = P(A) + P(B) - P(A $\cap$ B)

where A is the event that a random male has blue eyes and B is the event a random female has blue eyes.

Looking at the table on the blue row and blue column, P(A) = 114/204 and P(B) = 102/204 and P(A $\cap$ B) = 78/204

which equals 114/204 + 108/204 - 78/204 = 140/204 or 0.7058 or about 70.5%

b) Probability of a couple both having blue eyes based on the table is 78/204 = 0.3824 which is about 38.2%

c) Let C and D be the events of a male having brown eyes and a female of having blue eyes respectively.

then P(C $\cap$ D) when looking at the table shows 19/204 = 0.0931 or about 9.3%

Getting a randomly chosen male with green eyes and a partner with blue eyes looking at the table is

11/204 = 0.0539 or about 5.3%

d) The eye colors of male respondents and their partners is not independent as the probabilities of male partners

of each color are not the same.

2.30

a) Probability of drawing a hardcover book first is based on the table 28/95 = 0.2947

with sampling without replacement is one less book with 94 total books so probability of

finding paperback fiction book is now 59/94 = 0.6277

b) Probability of finding a fiction book first is 72/95 and probability of fining a hardcover book after is 27/94

as a hardcover book is taken leaving one less hardcover book and one less book overall.

c) the question is sampling with replacement using b) probability of picking a fiction book is 72/95 and as

the book is put back, the probability of picking a hardcover book after is 28/95.

d) they are similar as one book is being taken away and not much of the change in probability.

2.38

a) A probability model and expected value of average revenue is 25 $\cdot$ P(1 luggage) + 60 $\cdot$ P(2 luggages) =

25 $\cdot$ 0.34 + 60 $\cdot$ 0.12 = $15.7 and standard deviation is

-15.7^2 $\cdot$ 0.54 + (25 - 15.7)^2 $\cdot$ 0.34 + (60 - 15.7)^2 $\cdot$ 0.12 = 398.01

b) 




2.44

a) looking that the percentage totals for each income interval this is a approximately normally distributed.

b) by adding up the total (probabilities) up to 50k, we see that 2.2+4.7+15.8+18.3+21.2 = 62.2%

c) drawing a tree diagram starting with the probabilities of male and females and multiplying the 

P(female) * P(< 50,000/year) gives 0.41 $\cdot$ .622 = 0.0255 or about 2.5%

This is under the assumption that the percentage of males and females is consistent regardless of income bracket or range.

d) with P(female) = 0.718, computing the probability changes and is now 0.718 * .622 