;(function(window,document,undefined){var w,aa=aa||{};function ba(a,b,c){return a.call.apply(a.bind,arguments)}function ea(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function D(a,b,c){D=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ba:ea;return D.apply(null,arguments)}
var fa=aa.ya&&Date.now||function(){return+new Date};mti={bind:function(a,b,c){var d=2<arguments.length?Array.prototype.slice.call(arguments,2):[];return function(){d.push.apply(d,arguments);return b.apply(a,d)}}};function ga(a,b){this.i=b||a;this.a=this.i.document;this.c=void 0}w=ga.prototype;w.createElement=function(a,b,c){a=this.a.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?E(this,a,b[d]):a.setAttribute(d,b[d]));c&&a.appendChild(this.a.createTextNode(c));return a};function ha(a,b,c){a=a.a.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}w.ca=function(a){function b(){c.a.body?a():setTimeout(b,0)}var c=this;b()};
function ia(a){a.parentNode&&a.parentNode.removeChild(a)}function H(a,b){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var c=a.className.split(/\s+/),d=0,f=c.length;d<f;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}
function I(a,b){if(!("undefined"!==typeof SVGElement&&a instanceof SVGElement)){for(var c=a.className.split(/\s+/),d=[],f=0,e=c.length;f<e;f++)c[f]!=b&&d.push(c[f]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}}function ja(a,b){if("undefined"!==typeof SVGElement&&a instanceof SVGElement)return!1;for(var c=a.className.split(/\s+/),d=0,f=c.length;d<f;d++)if(c[d]==b)return!0;return!1}
function E(a,b,c){if(void 0===a.c){var d=a.a.createElement("p");d.innerHTML='<a style="top:1px;">w</a>';a.c=/top/.test(d.getElementsByTagName("a")[0].getAttribute("style"))}a.c?b.setAttribute("style",c):b.style.cssText=c}
w.getComputedStyle=function(a){if("undefined"!=typeof a&&null!=a){if(1!=a.nodeType)return"";var b={};if("undefined"!=typeof a.currentStyle&&null!=a.currentStyle)return b.fontFamily=a.currentStyle.fontFamily,b.fontWeight=a.currentStyle.fontWeight,b.fontStyle=a.currentStyle.fontStyle,b;a=this.a.defaultView.getComputedStyle(a,null);if("undefined"!=typeof a&&null!=a)return b.fontFamily=a.getPropertyValue("font-family"),b.fontWeight=a.getPropertyValue("font-weight"),b.fontStyle=a.getPropertyValue("font-style"),
b}return""};w.L=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.a.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};
function ka(a,b){if("undefined"!=typeof b&&null!=b){if("undefined"!=typeof b.currentStyle)return b.currentStyle.fontWeight;var c=a.a.defaultView.getComputedStyle(b,null);if(c){var d=c.getPropertyValue("font-weight");return"bold"==d.toLowerCase()?700:"normal"==d.toLowerCase()?400:c.getPropertyValue("font-weight")}}return""}
function la(a,b){if("undefined"!=typeof b&&null!=b){if("undefined"!=typeof b.currentStyle)return b.currentStyle.fontStyle;var c=a.a.defaultView.getComputedStyle(b,null);if(c)return c.getPropertyValue("font-style")}return""}w.getElementById=function(a){return this.a.getElementById(a)};w.indexOf=function(a,b){if(a){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;c++)if(a[c]==b)return c}return-1};function J(a){return a.replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|")}
w.L=function(a){if("undefined"!=typeof a&&null!=a){if("undefined"!=typeof a.currentStyle)return a.currentStyle.fontFamily;if(a=this.a.defaultView.getComputedStyle(a,null))return a.getPropertyValue("font-family")}return""};function M(a,b){this.c=a;this.a=b};function N(a,b,c,d){this.g=null!=a?a:null;this.m=null!=b?b:null;this.a=null!=c?c:null;this.c=null!=d?d:null}var ma=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;N.prototype.toString=function(){return[this.g,this.m||"",this.a||"",this.c||""].join("")};
function O(a){a=ma.exec(a);var b=null,c=null,d=null,f=null;a&&(null!==a[1]&&a[1]&&(b=parseInt(a[1],10)),null!==a[2]&&a[2]&&(c=parseInt(a[2],10)),null!==a[3]&&a[3]&&(d=parseInt(a[3],10)),null!==a[4]&&a[4]&&(/^[0-9]+$/.test(a[4])?f=parseInt(a[4],10):f=a[4]));return new N(b,c,d,f)};function P(a,b,c,d,f,e,g,k){this.D=a;this.oa=b;this.aa=f;this.a=k}P.prototype.getName=function(){return this.D};function na(){this.b=navigator.userAgent}var oa=new P("Unknown",new N,0,0,"Unknown",0,0,new M(!1,!1));
function pa(){var a=new na;if(-1!=a.b.indexOf("MSIE")||-1!=a.b.indexOf("Trident/")){var b=Q(a),c=O(qa(a)),d=null,f=R(a.b,/Trident\/([\d\w\.]+)/,1),d=-1!=a.b.indexOf("MSIE")?O(R(a.b,/MSIE ([\d\w\.]+)/,1)):O(R(a.b,/rv:([\d\w\.]+)/,1));""!=f&&O(f);a=new P("MSIE",d,0,0,b,0,0,new M("Windows"==b&&6<=d.g||"Windows Phone"==b&&8<=c.g,!1))}else if(-1!=a.b.indexOf("Opera"))a:if(b=O(R(a.b,/Presto\/([\d\w\.]+)/,1)),O(qa(a)),null!==b.g||O(R(a.b,/rv:([^\)]+)/,1)),-1!=a.b.indexOf("Opera Mini/"))b=O(R(a.b,/Opera Mini\/([\d\.]+)/,
1)),a=new P("OperaMini",b,0,0,Q(a),0,0,new M(!1,!1));else{if(-1!=a.b.indexOf("Version/")&&(b=O(R(a.b,/Version\/([\d\.]+)/,1)),null!==b.g)){a=new P("Opera",b,0,0,Q(a),0,0,new M(10<=b.g,!1));break a}b=O(R(a.b,/Opera[\/ ]([\d\.]+)/,1));a=null!==b.g?new P("Opera",b,0,0,Q(a),0,0,new M(10<=b.g,!1)):new P("Opera",new N,0,0,Q(a),0,0,new M(!1,!1))}else/OPR\/[\d.]+/.test(a.b)?a=sa(a):/AppleWeb(K|k)it/.test(a.b)?a=sa(a):-1!=a.b.indexOf("Gecko")?(b="Unknown",c=new N,O(qa(a)),d=!1,-1!=a.b.indexOf("Firefox")?(b=
"Firefox",c=O(R(a.b,/Firefox\/([\d\w\.]+)/,1)),d=3<=c.g&&5<=c.m):-1!=a.b.indexOf("Mozilla")&&(b="Mozilla"),f=O(R(a.b,/rv:([^\)]+)/,1)),d||(d=1<f.g||1==f.g&&9<f.m||1==f.g&&9==f.m&&2<=f.a),a=new P(b,c,0,0,Q(a),0,0,new M(d,!1))):a=oa;return a}
function Q(a){var b=R(a.b,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=R(a.b,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS|PlayStation|CrKey)/,1);return""!=a?("Mac_PowerPC"==a?a="Macintosh":"PlayStation"==a&&(a="Linux"),a):"Unknown"}
function qa(a){var b=R(a.b,/Windows Phone( OS)? ([^;)]+)/,2);if(b||(b=R(a.b,/(OS X|Windows NT|Android) ([^;)]+)/,2))||(b=R(a.b,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=R(a.b,/(?:Linux|CrOS|CrKey) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=R(a.b,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function sa(a){var b=Q(a),c=O(qa(a)),d=O(R(a.b,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1)),f="Unknown",e=new N,e="Unknown",g=!1;/OPR\/[\d.]+/.test(a.b)?f="Opera":-1!=a.b.indexOf("Edge")?f="Edge":-1!=a.b.indexOf("Chrome")||-1!=a.b.indexOf("CrMo")||-1!=a.b.indexOf("CriOS")?f="Chrome":/Silk\/\d/.test(a.b)?f="Silk":"BlackBerry"==b||"Android"==b?f="BuiltinBrowser":-1!=a.b.indexOf("PhantomJS")?f="PhantomJS":-1!=a.b.indexOf("Safari")?f="Safari":-1!=a.b.indexOf("AdobeAIR")?f="AdobeAIR":-1!=a.b.indexOf("PlayStation")?
f="BuiltinBrowser":-1!=a.b.indexOf("FBAN")&&(f="FBWebUI");"BuiltinBrowser"==f?e="Unknown":"Silk"==f?e=R(a.b,/Silk\/([\d\._]+)/,1):"Chrome"==f?e=R(a.b,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.b.indexOf("Version/")?e=R(a.b,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==f?e=R(a.b,/AdobeAIR\/([\d\.]+)/,1):"Opera"==f?e=R(a.b,/OPR\/([\d.]+)/,1):"PhantomJS"==f?e=R(a.b,/PhantomJS\/([\d.]+)/,1):"FBWebUI"==f?e=R(a.b,/FBSV\/([\d.]+)/,1):"Edge"==f&&(e=R(a.b,/Edge\/([\d.]+)/,1));e=O(e);g="AdobeAIR"==f?2<e.g||2==e.g&&
5<=e.m:"BlackBerry"==b?10<=c.g:"Android"==b?2<c.g||2==c.g&&1<c.m:526<=d.g||525<=d.g&&13<=d.m;return new P(f,e,0,0,b,0,0,new M(g,536>d.g||536==d.g&&11>d.m))}function R(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""};function ta(a){this.c=a||"-"}ta.prototype.a=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.c)};function ua(a,b,c){this.f=a;this.c=b;this.i=c;this.a=new ta("-")}function va(a){H(a.c,a.a.a("mti","loading"));T(a,"loading")}function wa(a){I(a.c,a.a.a("mti","loading"));ja(a.c,a.a.a("mti","active"))||H(a.c,a.a.a("mti","inactive"));T(a,"inactive")}function T(a,b,c){if(a.i[b])if(c)a.i[b](c.getName(),U(c));else a.i[b]()};function V(a,b){this.D=a;this.F=4;this.B="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.B=c[1],this.F=parseInt(c[2],10))}V.prototype.getName=function(){return this.D};V.prototype.ba=function(a){var b=[];a=a.split(/,\s*/);for(var c=0;c<a.length;c++){var d=a[c].replace(/['"]/g,"");-1==d.indexOf(" ")?b.push(d):b.push("'"+d+"'")}return b.join(",")};function U(a){return a.B+a.F};function xa(a,b){this.f=a;this.c=b;this.a=this.f.createElement("span",{"aria-hidden":"true"},this.c)}function ya(a){ha(a.f,"body",a.a)}function za(a){var b="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+a.ba(a.D)+"!important;",c="normal",d=a.F+"00";"o"===a.B?c="oblique":"i"===a.B&&(c="italic");return b+("font-style:"+c+";font-weight:"+d+";")};function Aa(a,b,c,d,f,e,g,k){this.M=a;this.ha=b;this.f=c;this.a=d;this.I=k||"BESb\uc5d0swy";this.O=f;this.l={};this.ja=e||5E4;this.N=g||null;this.i=this.c=null;a=new xa(this.f,this.I);ya(a);for(var m in W)W.hasOwnProperty(m)&&(b=new V(W[m],U(this.a)),E(a.f,a.a,za(b)),this.l[W[m]]=a.a.offsetWidth);ia(a.a)}var W={xa:"serif",wa:"sans-serif",sa:"monospace"};function Ba(a,b,c){for(var d in W)if(W.hasOwnProperty(d)&&b===a.l[W[d]]&&c===a.l[W[d]])return!0;return!1}
function Ca(a){var b=a.c.a.offsetWidth,c=a.i.a.offsetWidth;b===a.l.serif&&c===a.l["sans-serif"]||a.O.a&&Ba(a,b,c)?fa()-a.ia>=a.ja?a.O.a&&Ba(a,b,c)&&(null===a.N||a.N.hasOwnProperty(a.a.getName()))?Ea(a,a.M):Ea(a,a.ha):Fa(a):Ea(a,a.M)}function Fa(a){setTimeout(D(function(){Ca(this)},a),25)}function Ea(a,b){ia(a.c.a);ia(a.i.a);b(a.a)};function Ga(a,b,c,d){this.f=b;this.a=c;this.c=0;this.l=this.i=!1;this.O=d;this.N=a.a}
function Ha(a,b,c,d,f){if(0===b.length&&f)wa(a.a);else for(a.c+=b.length,f&&(a.i=f),f=0;f<b.length;f++){var e=b[f],g=c[e.getName()],k=a.a,m=e;H(k.c,k.a.a("mti",m.getName(),U(m).toString(),"loading"));T(k,"fontloading",m);e=new Aa(D(a.I,a),D(a.M,a),a.f,e,a.N,a.O,d,g);e.c=new xa(e.f,e.I);ya(e.c);e.i=new xa(e.f,e.I);ya(e.i);e.ia=fa();g=e.c;k=new V(e.a.getName()+",serif",U(e.a));E(g.f,g.a,za(k));g=e.i;k=new V(e.a.getName()+",sans-serif",U(e.a));E(g.f,g.a,za(k));Ca(e)}}
Ga.prototype.I=function(a){var b=this.a;I(b.c,b.a.a("mti",a.getName(),U(a).toString(),"loading"));I(b.c,b.a.a("mti",a.getName(),U(a).toString(),"inactive"));H(b.c,b.a.a("mti",a.getName(),U(a).toString(),"active"));T(b,"fontactive",a);this.l=!0;Ia(this)};Ga.prototype.M=function(a){var b=this.a;I(b.c,b.a.a("mti",a.getName(),U(a).toString(),"loading"));ja(b.c,b.a.a("mti",a.getName(),U(a).toString(),"active"))||H(b.c,b.a.a("mti",a.getName(),U(a).toString(),"inactive"));T(b,"fontinactive",a);Ia(this)};
function Ia(a){0==--a.c&&a.i&&(a.l?(a=a.a,I(a.c,a.a.a("mti","loading")),I(a.c,a.a.a("mti","inactive")),H(a.c,a.a.a("mti","active")),T(a,"active")):wa(a.a))};mti.pa=function(){this.ba='"'};mti.j=function(){this.P=mti.j.c;this.s=mti.j.i};mti.j.c=["font-style","font-weight"];mti.j.i={"font-style":[["n","normal"]],"font-weight":[["4","normal"]]};mti.j.a=function(a,b,c){this.X=a;this.la=b;this.s=c};mti.j.a.prototype.compact=function(a,b){for(var c=0;c<this.s.length;c++)if(b==this.s[c][1]){a[this.X]=this.s[c][0];break}};mti.j.a.prototype.expand=function(a,b){for(var c=0;c<this.s.length;c++)if(b==this.s[c][0]){a[this.X]=this.la+":"+this.s[c][1];break}};
mti.j.prototype.compact=function(a){var b=["n","4"];a=a.split(";");for(var c=0,d=a.length;c<d;c++){var f=a[c].replace(/\s+/g,"").split(":");if(2==f.length){var e=f[1];a:{for(var f=f[0],g=0;g<this.P.length;g++)if(f==this.P[g]){f=new mti.j.a(g,f,this.s[f]);break a}f=null}f&&f.compact(b,e)}}return b.join("")};
mti.j.prototype.expand=function(a){if(2!=a.length)return null;for(var b=[null,null],c=0,d=this.P.length;c<d;c++){var f=this.P[c];(new mti.j.a(c,f,this.s[f])).expand(b,a.substr(c,1))}return b[0]&&b[1]?b.join(";")+";":null};function Ja(a,b,c){this.i=a;this.V=b;this.b=c;this.a=this.c=0}Ja.prototype.load=function(a){var b=a.context||this.i;this.f=new ga(this.i,b);b=new ua(this.f,b.document.documentElement,a);if(this.b.a.c){var c=this.V,d=this.f,f=[],e;for(e in a)if(a.hasOwnProperty(e)){var g=c.a[e];g&&f.push(g(a[e],d))}a=a.timeout;this.a=this.c=f.length;a=new Ga(this.b,this.f,b,a);e=0;for(c=f.length;e<c;e++)d=f[e],d.na(this.b,D(this.l,this,d,b,a))}else wa(b)};
Ja.prototype.l=function(a,b,c,d){var f=this;d?a.load(function(a,d,k){Ka(f,b,c,a,d,k)}):(a=0==--this.c,this.a--,a&&(0==this.a?wa(b):va(b)),Ha(c,[],{},null,a))};function Ka(a,b,c,d,f,e){var g=0==--a.c;g&&va(b);setTimeout(function(){Ha(c,d,f||{},e||null,g)},0)};var La=window,Ma=pa(),Na=La.MonoTypeWebFonts=new Ja(window,new function(){this.a={}},Ma);window.MonoTypeWebFonts.load=Na.load;mti.ra=4E4;
mti.u=function(a,b,c,d,f){this.v=a;this.b=b;this.f=c;this.h=d;this.da={};this.$=f;this.o=[];this.T=!1;this.K={};this.C=d.efg;this.v.mti_element_cache=[];this.version=this.G=void 0;this.w=!1;this.U={TTF:"truetype",WOFF:"woff",SVG:"svg",MTX:"truetype",OTF:"opentype",WOFF2:"woff2"};1==Y.UseTextIndent?this.J="text-align:left;text-indent:-9999px;font-size:0px":this.J="visibility:hidden;";this.G=a=this.b.getName().toLowerCase();this.version=this.b.oa;this.S="opera"===a&&15>this.version.g?!0:!1;this.w="msie"===
a&&8>=this.version.g?!0:!1;this.R={EOT:2,SVG:11,OTF:13,TTF:1,WOFF:3,WOFF2:14}};mti.u.a="monotype";mti.u.c=!1;mti.u.prototype={na:function(a,b){var c=this,d=c.h.projectId,f;if(d){c.v.mti_element_cache=[];Oa(c);this.ca(function(){var a=new Pa(document.body,c.f,c.h.pfL,!0);a.ea(document.body);var d=f=a.fa(),e="TTF",g=c.h.projectId,k=c.h.fcURL,m=Z(c,"dfcURL"),n=c.f.createElement("style",{type:"text/css",id:"mti_fontface_"+c.h.projectId}),h="";c.K={};var p=null,l=null;d||(d=[]);for(var z=0;z<c.h.pfL.length;z++){var e=c.h.pfL[z],x=e.fontfamily,u=e.contentIds,q=e.enableOtf,A=e.enableSubsetting,r=e.subsetOption,
C=null;c.C&&(p=e.fontWeight,l=e.fontStyle,C=l.charAt(0)+p/100,c.T=!0);var t=Z(c,"ffArray"),v=c.G,e=c.version.g+c.version.m/10;"firefox"==c.G&&(v="mozilla");/ipad|ipod|iphone/.test(c.b.aa.toLowerCase())&&(v="msafari");var t=t[v],v="",F=void 0;for(F in t)parseFloat(e)>=parseFloat(F)&&u[t[F].toUpperCase()]&&(v=t[F]);""===v&&(v="ttf");e=v;t=!0;if(0<d.length||c.S||!A){t=c.S||!A?!0:!1;for(A=0;A<d.length;A++)if(d[A].fontfamily==x&&(null!=p?d[A].F==p/100:1)&&(null!=l?d[A].B==l.charAt(0):1)){C=null==C?new V(x):
new V(x,C);c.o.push(C);t=!0;break}if(t){var C="",A=c,t=u,v=g,F=k,C=m,Da=c.h.ck,X=e,Ta=q,q=r,da=t[X.toUpperCase()],S=void 0,F=F.replace("http://","").replace("https://","");A.Y(q)?(C=C.replace("http://","").replace("https://",""),da=t.TTF,C="https://"+C+"?"+Da+"&fctypeId="+("15"==Z(A,"fctypeArray")[Qa(A)]?"3":Z(A,"fctypeArray")[Qa(A)])+"&fcId="+da+"&env="+A.h.env+"&projectId="+v,void 0!=q&&(A=q.unicode,t=q.text,q=q.lang,void 0!=A&&(C+="&ranges="+encodeURIComponent(A)),void 0!=t&&(C+="&content="+t.replace('"',
"%22").replace("'","%27").replace("#","%23").replace("?","%3F")),void 0!=q&&(C+="&languages="+q)),S=C):(F="https://"+F+(Ta?"ot/":""),""!==A.R[X.toUpperCase()]?F+=A.R[X.toUpperCase()]+"/":F+=A.R.WOFF+"/",S=F+da+"."+X.toLowerCase()+"?"+Da,S+="&projectId="+v,null!=X&&"SVG"==X.toUpperCase()&&(S+="#"+da));if(C=S)q="",c.w&&c.C&&(q="_"+l.charAt(0)+p/100,c.K[x]=x+q),void 0!=r&&(e=Qa(c)),h=Ra(c,x,"",h,p,l,x,C,e,u,!0,"",!1,!0,void 0,q,!1)}}}""!=h&&ha(c.f,"head",n);n.styleSheet?n.styleSheet.cssText=h:n.appendChild(document.createTextNode(h));
c.v.mti_element_cache=a.H;a=c.v.mti_element_cache;for(d=0;d<a.length;d++)for(var ra in c.K)if(-1<c.f.L(a[d]).indexOf(ra)){void 0==a[d].getAttribute("id");p=c.f;g=a[d];k=ra;h=c.K[ra];m=c.w;l=c.T;n=[];z=p.L(g).split(",");q=e="";x=void 0;a:if(x=!1,z instanceof Array)for(u=0;u<z.length;u++)if(h instanceof Array)for(r=0;r<h.length;r++){if(J(z[u])==J(h[r])){x=!0;break a}}else{if(J(z[u])==J(h)){x=!0;break}}else if(h instanceof Array)for(u=0;u<h.length;u++)if(z==h[u]){x=!0;break}if(!x){if(h instanceof Array)for(e=
0;e<z.length;e++)if(J(z[e])!=k)if(-1<J(z[e]).indexOf(k))for(q=0;q<h.length;q++)""!=h[q]&&(n.push(h[q]),n.push(k));else n.push(z[e]);else if(h instanceof Array)for(q=0;q<h.length;q++)""!=h[q]&&(m?l?(x=la(p,g),u=ka(p,g),r=J(h[q])+"_"+x.charAt(0)+u/100,n.push(r)):n.push(h[q]):n.push(h[q]),n.push(k));else n.push(h),n.push(k);else if(m)l?(x=la(p,g),u=ka(p,g),p=J(p.L(g)),r=k+"_"+x.charAt(0)+u/100,J(h),h=r.length,h=r.slice(h-2,h),e=100*h.charAt(1),q=h.charAt(0),k==p&&x.charAt(0)==q&&u==e&&(n.push(r),n.push(k))):
(n.push(h),n.push(k));else for(e=0;e<z.length;e++)if(J(z[e])!=k)0==J(z[e]).indexOf(k)?""!=h&&(n.push(h),n.push(k)):(n.push(z[e]),n.push(k));else if(h instanceof Array)for(q=0;q<h.length;q++)""!=h[q]&&(m?l?(x=la(p,g),u=ka(p,g),r=J(h[q])+"_"+x.charAt(0)+u/100,n.push(r)):n.push(h[q]):n.push(h[q]),n.push(k));else n.push(h),n.push(k);h={};p=[];l=0;for(z=n.length;l<z;++l)h.hasOwnProperty(J(n[l]))||(p.push(J(n[l])),h[J(n[l])]=1);n=p;if(0<n.length&&n[0]!=k){h="";for(e=0;e<n.length;e++)h+="'"+n[e]+"'",e!=
n.length-1&&(h+=",");h+="";g.setAttribute("data-mtiFont",k);m?(g.style.fontWeight="",g.style.fontStyle="",g.style.fontFamily=""+h):(k=""+h,g.style.setProperty?g.style.setProperty("font-family",""):g.style.setAttribute("font-family",""),g.setAttribute("style",g.style.cssText+"font-family:"+k+" !important;"))}}}b(Y.EnableCustomFOUTHandler)});1==Y.EnableCustomFOUTHandler&&(document.documentElement.style.visibility="hidden",setTimeout(function(){document.documentElement.style.visibility=""},750));var e=
[];f&&(e=f);var g=null;"function"===typeof c.v["__MonotypeConfiguration__"+d]&&(g=c.v["__MonotypeConfiguration__"+d]());if(void 0!==g||null!==g)loadAllFonts=g.loadAllFonts;if(c.S||loadAllFonts)for(e=[],g=0;g<c.h.pfL.length;g++){var k,m,r,v=c.h.pfL[g].fontfamily;void 0!=c.h.pfL[g].fontWeight&&void 0!=c.h.pfL[g].fontStyle&&(r=c.h.pfL[g].fontStyle,m=c.h.pfL[g].fontWeight,k=r.charAt(0)+m/100,c.w&&(v=v+"_"+r.charAt(0)+m/100,m="400",r="normal",k="n4"));var t=new V(v,k);t.fontfamily=v;t.fontWeight=m;t.fontStyle=
r;e.push(t)}c.v["__mti_fntLst"+d]=function(){for(var a=[],c=[],b=0;b<e.length;b++)a.push({fontfamily:e[b].D,fontStyle:e[b].B,fontWeight:e[b].F}),c.push(e[b]);return a}}else b(Y.EnableCustomFOUTHandler)}};MonoTypeWebFonts.V.a[mti.u.a]=function(a){var b=pa(),c=new ga(window),d=null;a.enableOtf&&(d=new mti.ta(c,b,a));b=new mti.u(window,b,c,a,d);if(a.reqSub||Y.EnableDSForAllFonts||a.enableOtf){var f=new mti.ua(b);window.MonoTypeWebFonts.renderPartial=function(a,c){f.Ca(a,c)}}return b};
var Sa={ec:"true",dfcURL:"http://api2.fonts.com/FontSubsetter.ashx",fontdataversion:"v2",sO:"true",ffArray:{safari:{"3.1":"ttf","5.1":"woff"},msafari:{1:"svg","4.2":"ttf","5.1":"woff"},chrome:{3:"svg",4:"ttf",5:"woff",36:"woff2"},opera:{10:"ttf","11.10":"woff","26.0":"woff2"},msie:{4:"eot",9:"woff"},mozilla:{"3.5":"ttf","3.6":"woff","39.0":"woff2"},edge:{12:"woff"}},bsmcArray:{safari:{"3.1":"2000","5.1":"15600"},msafari:{1:"15600"},chrome:{3:"15600"},opera:{10:"15600"},msie:{4:"1000",9:"3000"},mozilla:{"3.5":"15600"},
edge:{12:"15600"}},fctypeArray:{ttf:"1",eot:"2",woff:"3",svg:"11",otf:"13",woff2:"14"},specialChar:"%u201C %u201D %u2200 %u2202 %u2203 %u2205 %u2207 %u2208 %u2209 %u220B %u220F %u2211 %u2018 %u2019 %B0 %u2026 %u2122 %A9 %AE %u2014 %u2013 %A7 %B1 %B7 %u2032 %u2033 %u20AC %u2248 %u2260 %u2264 %u2265 %u221A %u221D %u2220 %u2225 %u2227 %u2228 %u2229 %u222A %u222B %u222E %u2234 %u2235 %u2236 %u2237 %u223D %u224C %u2261 %u226E %u226F %u2299 %u22A5 %u0391 %u0392 %u0393 %u0394 %u0395 %u0396 %u0397 %u0398 %u0399 %u039A %u039B %u039C %u039D %u039E %u039F %u03A0 %u03A1 %u03A3 %u03A4 %u03A5 %u03A6 %u03A7 %u03A8 %u03A9 %u221E %u2190 %u2191 %u2192 %u2193 %u2640 %u2642 + %22 %5C %23 %26 %3F %B7 %3B %3A".split(" ")};
function Z(a,b){return void 0!=Sa[b]?Sa[b]:a.h[b]};mti.u.prototype.load=function(a){a(this.o,this.da)};
function Oa(a){var b=new ta("-"),c=a.f.createElement("style",{type:"text/css",id:"mti_stylesheet_"+a.h.projectId}),d="";if(1==Y.EnableCustomFOUTHandler||1==Y.UseHybrid){for(var f=a.h.pfL,d=d+(".mti-loading .mti_font_element{"+a.J+"}\n"),e=0;e<f.length;e++){var g=f[e].fontfamily,k="4",m="n";a.C&&(k=f[e].fontWeight/100,m=f[e].fontStyle.charAt(0),a.w&&(g=g+"_"+m+k,k="4",m="n"));g&&(d+="."+b.a("mti",g,m+k,"loading")+" .mti_font_element{"+a.J+"}\n")}d+=".mti_hide_element{"+a.J+"}"}for(e in a.h.selectorFontMap)if(b=
a.h.selectorFontMap[e],g=b.familyName,a.C?(m=b.fontStyle,k=b.fontWeight):(m="normal",k="400"),d=Ra(a,g,e,d,k,m,"","","","",!1,b,!0),1==Y.EnableCustomFOUTHandler)for(k in d+="/*fout specific code:*/\n",g=e.split(","),k=void 0,g)d+=".mti-loading "+g[k]+"{"+a.J+"}\n";""!=d&&ha(a.f,"head",c);c.styleSheet?c.styleSheet.cssText=d:c.appendChild(document.createTextNode(d))}
function Ra(a,b,c,d,f,e,g,k,m,r,v,t,ca,G,y,K,L){1<a.f.indexOf(g,y)?y="":"";G?d+='@font-face{\nfont-family:"'+g+(y?y:"")+(K?K:"")+'";':"";a.w&&a.C&&!L&&(b+="_"+e.charAt(0)+f/100);G?"":d+=c+"{font-family:'"+b+"';";0==a.w&&a.C&&!L&&(d=d+("\n font-style:"+e+";")+("\n font-weight:"+f+";"));k?d+='\nsrc:url("'+k+'")':"";v?(b=d,null!=m&&"EOT"==m.toUpperCase()||"MTX"==m.toUpperCase()||(c=a.U[m.toUpperCase()],r[m.toUpperCase()]||(c=a.U.TTF),b+=" format('"+c+"')"),d=b):"";ca?(m=d,null!=a.$&&(r=t.otf,t=t.vrnt,
r&&null!=r&&""!=r&&(m+=a.$.za(r,t))),d=m):"";return d+=";}\n"}mti.u.prototype.ca=function(a){function b(){document.body?a():setTimeout(b,0)}b()};function Qa(a){var b=Z(a,"ffArray"),c=a.G,d=a.version.g+a.version.m/10;"firefox"==a.G&&(c="mozilla");/ipad|ipod|iphone/.test(a.b.aa.toLowerCase())&&(c="msafari");a=b[c];var b="",f;for(f in a)parseFloat(d)>=parseFloat(f)&&(b=a[f]);""===b&&(b="ttf");return b}
mti.u.prototype.Y=function(a){var b=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?b=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?b=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text&&(b=!0));return b};var Y=window.MTIConfig||{Ba:!1,qa:!1,va:!1};function Pa(a,b,c,d){this.ma=a;this.f=b;this.ka=c;this.A={};this.H=[];this.o=[];d?this.Z=d:!1;this.ga="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ")}
Pa.prototype=function(){function a(a){var b=!1;void 0!=typeof a&&null!=a&&""!=a&&(void 0!=typeof a.lang&&null!=a.lang&&""!=a.lang?b=!0:void 0!=typeof a.unicode&&null!=a.unicode&&""!=a.unicode?b=!0:void 0!=typeof a.text&&null!=a.text&&""!=a.text&&(b=!0));return b}function b(a,d,f){if(void 0!==a&&null!==a&&""!==a&&a.tagName&&1===a.nodeType)for(0>f.f.indexOf(f.ga,a.tagName.toLowerCase())&&(d?f.W(a,d):f.W(a)),a=a.firstChild;a;)b(a,d,f),a=a.nextSibling}return{W:function(b,d){var f=this.ka,e=this.f.getComputedStyle(b),
g=e.fontFamily,k="",m=e.fontStyle,r=0,v=0,t="",g=(g||"").replace(/^\s|\s$/g,"").replace(/'|"/g,"").replace(/,\s*/g,"|");if(""!=g)for(var ca=g.split("|"),G="",r=0;r<ca.length;r++)for(v=0;v<f.length;v++){var y=f[v],G=y.fontfamily,K,L,B=y.enableSubsetting,n=y.enableOtf,h=y.contentIds,p=y.subsetOption,l=!1,z=G,x=new RegExp("^("+ca[r]+")$","ig");if(void 0!=y.fontWeight&&void 0!=y.fontStyle)K=y.fontWeight,L=y.fontStyle,t=L.charAt(0)+K/100,k="normal"==e.fontWeight?400:"bold"==e.fontWeight?700:e.fontWeight;
else{var u="h1 h2 h3 h4 h5 h6 strong b".split(" ");1==b.nodeType&&(k=0<=this.f.indexOf(u,b.tagName.toLowerCase())?400:"normal"==e.fontWeight?400:"bold"==e.fontWeight?700:400)}if(void 0!=K||void 0!=L)z+="_"+t;var u=G.replace(/^\s|\s$/g,""),q=z.replace(/^\s|\s$/g,""),A=x.test(u),x=x.test(q);if(A||x)if(void 0!=K||void 0!=L?z==g?(l=new V(q),l.fontfamily=u,l.fontWeight=K,l.fontStyle=L,l.enableSubsetting=B,l.contentIds=h,l.enableOtf=n,l.subsetOption=p,this.o.push(l),this.H.push(b),l=!0):k==K&&m==L&&(l=
new V(u,t),l.fontfamily=u,l.fontWeight=K,l.fontStyle=L,l.enableSubsetting=B,l.contentIds=h,l.enableOtf=n,l.subsetOption=p,this.o.push(l),this.H.push(b),l=!0):(t="n4",l=new V(u),l.fontfamily=u,l.fontWeight=k/100,l.fontStyle=m.charAt(0),l.enableSubsetting=B,l.contentIds=h,l.enableOtf=n,l.subsetOption=p,this.o.push(l),this.H.push(b),l=!0),l&&(1==Y.EnableCustomFOUTHandler&&H(b,d?"mti_font_element"+d:"mti_font_element"),B=b.getAttribute("style"),(B=null!=B?"string"==typeof B?B:"cssText"in B?B.cssText:
"":"")&&-1<this.f.indexOf(B,"font-weight")&&-1<this.f.indexOf(B,"font-style")?G+="_"+m.charAt(0)+k/100:G+=1<t.length?"_"+t:"",!this.Z&&(y.enableSubsetting||Y.EnableDSForAllFonts)&&!a(p))){y="";y=this.f;p=b;B="";if(void 0!=typeof p&&null!=p){void 0!=p&&null!=p&&"INPUT"==p.tagName&&(B+=p.value);p=p.childNodes||p;n="img script noscript iframe object style param embed link meta head title br hr svg path".split(" ");for(h=0;h<p.length;h++)8!=p[h].nodeType&&0>y.indexOf(n,p[h].tagName?p[h].tagName.toLowerCase():
"")&&(l=(l=p[h].parentNode)?"undefined"!=typeof l.currentStyle?l.currentStyle.textTransform:(l=y.a.defaultView.getComputedStyle(l,null))?l.getPropertyValue("text-transform"):"":void 0,"none"!=l?(l=1!=p[h].nodeType?p[h].nodeValue.replace(/(?:\r\n|\r|\n)/g," "):"",B+=l.toLowerCase()+l.toUpperCase()):B+=1!=p[h].nodeType?p[h].nodeValue.replace(/(?:\r\n|\r|\n)/g," "):"");y=B}else y=void 0;this.A[G.replace(/^\s|\s$/g,"")]&&(y+=this.A[G.replace(/^\s|\s$/g,"")]);this.A[G.replace(/^\s|\s$/g,"")]=y}}},ea:function(a,
d){b(this.ma,d,this);var f=!1,e;for(e in this.A)if(f=!0,this.Z)break;else{var g;if((g=this.A[e])&&"string"==typeof g){for(var k="",m=g.length,r=null,v=0;v<m;v++)r=g.charAt(v),-1==k.indexOf(r)&&(k+=r);g=k}else g="";this.A[e]=g}return f?this.A:null},fa:function(){var a=this.o,b=null==a?0:a.length,f={},e,g=[];for(e=0;e<b;e+=1)f[a[e].D+"||"+a[e].F+"||"+a[e].B]=a[e];for(e in f)g.push(f[e]);return this.o=g},Aa:function(){return this.H},Y:a}}();
})(this,document);